# typed: false
# frozen_string_literal: true

# rubocop:disable RSpec/DescribeClass
require "spec_helper"

RSpec.describe "JSON Schema code generation", type: :integration do
  describe "basic object schema" do
    let(:schema) do
      {
        "type" => "object",
        "title" => "User",
        "properties" => {
          "name" => { "type" => "string" },
          "age" => { "type" => "integer" }
        },
        "required" => ["name"]
      }
    end

    it "generates T::Struct code" do
      code = Skit::JsonSchema.generate(schema, module_name: "BasicTest")

      expected = <<~RUBY.chomp
        # typed: strict
        # frozen_string_literal: true

        # This file is autogenerated by skit
        # DO NOT EDIT MANUALLY

        require "sorbet-runtime"

        module BasicTest

          class User < T::Struct
            prop :name, String
            prop :age, T.nilable(Integer)
          end
        end
      RUBY

      expect(code).to eq(expected)
    end
  end

  describe "nested object schema" do
    let(:schema) do
      {
        "type" => "object",
        "title" => "User",
        "properties" => {
          "name" => { "type" => "string" },
          "address" => {
            "type" => "object",
            "properties" => {
              "city" => { "type" => "string" },
              "zip" => { "type" => "string" }
            },
            "required" => ["city"]
          }
        },
        "required" => ["name"]
      }
    end

    it "generates nested T::Struct code" do
      code = Skit::JsonSchema.generate(schema, module_name: "NestedTest")

      expected = <<~RUBY.chomp
        # typed: strict
        # frozen_string_literal: true

        # This file is autogenerated by skit
        # DO NOT EDIT MANUALLY

        require "sorbet-runtime"

        module NestedTest

          class UserAddress < T::Struct
            prop :city, String
            prop :zip, T.nilable(String)
          end

          class User < T::Struct
            prop :name, String
            prop :address, T.nilable(UserAddress)
          end
        end
      RUBY

      expect(code).to eq(expected)
    end
  end

  describe "array schema" do
    let(:schema) do
      {
        "type" => "object",
        "title" => "Container",
        "properties" => {
          "tags" => {
            "type" => "array",
            "items" => { "type" => "string" }
          },
          "items" => {
            "type" => "array",
            "items" => {
              "type" => "object",
              "properties" => {
                "name" => { "type" => "string" }
              },
              "required" => ["name"]
            }
          }
        },
        "required" => ["tags"]
      }
    end

    it "generates array type code" do
      code = Skit::JsonSchema.generate(schema, module_name: "ArrayTest")

      expected = <<~RUBY.chomp
        # typed: strict
        # frozen_string_literal: true

        # This file is autogenerated by skit
        # DO NOT EDIT MANUALLY

        require "sorbet-runtime"

        module ArrayTest

          class ContainerItemsItem < T::Struct
            prop :name, String
          end

          class Container < T::Struct
            prop :tags, T::Array[String]
            prop :items, T.nilable(T::Array[ContainerItemsItem])
          end
        end
      RUBY

      expect(code).to eq(expected)
    end
  end

  describe "date/time format schema" do
    let(:schema) do
      {
        "type" => "object",
        "title" => "Event",
        "properties" => {
          "name" => { "type" => "string" },
          "date" => { "type" => "string", "format" => "date" },
          "starts_at" => { "type" => "string", "format" => "date-time" },
          "time" => { "type" => "string", "format" => "time" }
        },
        "required" => %w[name date]
      }
    end

    it "generates date/time type code" do
      code = Skit::JsonSchema.generate(schema, module_name: "DateTest")

      expected = <<~RUBY.chomp
        # typed: strict
        # frozen_string_literal: true

        # This file is autogenerated by skit
        # DO NOT EDIT MANUALLY

        require "sorbet-runtime"

        module DateTest

          class Event < T::Struct
            prop :name, String
            prop :date, Date
            prop :starts_at, T.nilable(DateTime)
            prop :time, T.nilable(Time)
          end
        end
      RUBY

      expect(code).to eq(expected)
    end
  end

  describe "enum schema" do
    let(:schema) do
      {
        "type" => "object",
        "title" => "Task",
        "properties" => {
          "title" => { "type" => "string" },
          "status" => {
            "type" => "string",
            "enum" => %w[pending in_progress completed]
          },
          "priority" => {
            "type" => "integer",
            "enum" => [1, 2, 3]
          }
        },
        "required" => %w[title status]
      }
    end

    it "generates T::Enum code" do
      code = Skit::JsonSchema.generate(schema, module_name: "EnumTest")

      expected = <<~RUBY.chomp
        # typed: strict
        # frozen_string_literal: true

        # This file is autogenerated by skit
        # DO NOT EDIT MANUALLY

        require "sorbet-runtime"

        module EnumTest

          class Status < T::Enum
            enums do
              Pending = new("pending")
              InProgress = new("in_progress")
              Completed = new("completed")
            end
          end

          class Priority < T::Enum
            enums do
              Val1 = new(1)
              Val2 = new(2)
              Val3 = new(3)
            end
          end

          class Task < T::Struct
            prop :title, String
            prop :status, Status
            prop :priority, T.nilable(Priority)
          end
        end
      RUBY

      expect(code).to eq(expected)
    end
  end

  describe "const schema" do
    let(:schema) do
      {
        "type" => "object",
        "title" => "Dog",
        "properties" => {
          "type" => { "const" => "dog" },
          "name" => { "type" => "string" },
          "status" => { "const" => 200 },
          "enabled" => { "const" => true }
        },
        "required" => %w[type name]
      }
    end

    it "generates Const class code" do
      code = Skit::JsonSchema.generate(schema, module_name: "ConstTest")

      expected = <<~RUBY.chomp
        # typed: strict
        # frozen_string_literal: true

        # This file is autogenerated by skit
        # DO NOT EDIT MANUALLY

        require "sorbet-runtime"
        require "skit"

        module ConstTest

          class TypeDog < Skit::JsonSchema::Types::Const
            VALUE = "dog"
          end

          class StatusVal200 < Skit::JsonSchema::Types::Const
            VALUE = 200
          end

          class EnabledTrue < Skit::JsonSchema::Types::Const
            VALUE = true
          end

          class Dog < T::Struct
            prop :type, TypeDog
            prop :name, String
            prop :status, T.nilable(StatusVal200)
            prop :enabled, T.nilable(EnabledTrue)
          end
        end
      RUBY

      expect(code).to eq(expected)
    end
  end

  describe "oneOf with objects (discriminated union)" do
    let(:schema) do
      {
        "type" => "object",
        "title" => "Container",
        "properties" => {
          "data" => {
            "oneOf" => [
              {
                "type" => "object",
                "properties" => {
                  "type" => { "const" => "dog" },
                  "breed" => { "type" => "string" }
                },
                "required" => %w[type breed]
              },
              {
                "type" => "object",
                "properties" => {
                  "type" => { "const" => "cat" },
                  "color" => { "type" => "string" }
                },
                "required" => %w[type color]
              }
            ]
          }
        },
        "required" => ["data"]
      }
    end

    it "generates union type code" do
      code = Skit::JsonSchema.generate(schema, module_name: "UnionTest")

      expected = <<~RUBY.chomp
        # typed: strict
        # frozen_string_literal: true

        # This file is autogenerated by skit
        # DO NOT EDIT MANUALLY

        require "sorbet-runtime"
        require "skit"

        module UnionTest

          class TypeDog < Skit::JsonSchema::Types::Const
            VALUE = "dog"
          end

          class TypeCat < Skit::JsonSchema::Types::Const
            VALUE = "cat"
          end

          class ContainerDataVariant0 < T::Struct
            prop :type, TypeDog
            prop :breed, String
          end

          class ContainerDataVariant1 < T::Struct
            prop :type, TypeCat
            prop :color, String
          end

          class Container < T::Struct
            prop :data, T.any(ContainerDataVariant0, ContainerDataVariant1)
          end
        end
      RUBY

      expect(code).to eq(expected)
    end
  end

  describe "anyOf with nullable" do
    let(:schema) do
      {
        "type" => "object",
        "title" => "Response",
        "properties" => {
          "value" => {
            "anyOf" => [
              { "type" => "string" },
              { "type" => "null" }
            ]
          }
        },
        "required" => ["value"]
      }
    end

    it "generates nilable type code" do
      code = Skit::JsonSchema.generate(schema, module_name: "NullableTest")

      expected = <<~RUBY.chomp
        # typed: strict
        # frozen_string_literal: true

        # This file is autogenerated by skit
        # DO NOT EDIT MANUALLY

        require "sorbet-runtime"

        module NullableTest

          class Response < T::Struct
            prop :value, T.nilable(String)
          end
        end
      RUBY

      expect(code).to eq(expected)
    end
  end

  describe "$ref support" do
    let(:schema) do
      {
        "type" => "object",
        "title" => "Order",
        "$defs" => {
          "Address" => {
            "type" => "object",
            "properties" => {
              "city" => { "type" => "string" }
            },
            "required" => ["city"]
          }
        },
        "properties" => {
          "id" => { "type" => "integer" },
          "shipping" => { "$ref" => "#/$defs/Address" },
          "billing" => { "$ref" => "#/$defs/Address" }
        },
        "required" => %w[id shipping]
      }
    end

    it "generates code with resolved $ref" do
      code = Skit::JsonSchema.generate(schema, module_name: "RefTest")

      expected = <<~RUBY.chomp
        # typed: strict
        # frozen_string_literal: true

        # This file is autogenerated by skit
        # DO NOT EDIT MANUALLY

        require "sorbet-runtime"

        module RefTest

          class OrderShipping < T::Struct
            prop :city, String
          end

          class OrderBilling < T::Struct
            prop :city, String
          end

          class Order < T::Struct
            prop :id, Integer
            prop :shipping, OrderShipping
            prop :billing, T.nilable(OrderBilling)
          end
        end
      RUBY

      expect(code).to eq(expected)
    end
  end

  describe "without module name" do
    let(:schema) do
      {
        "type" => "object",
        "title" => "Simple",
        "properties" => {
          "name" => { "type" => "string" }
        },
        "required" => ["name"]
      }
    end

    it "generates code without module wrapper" do
      code = Skit::JsonSchema.generate(schema)

      expected = <<~RUBY.chomp
        # typed: strict
        # frozen_string_literal: true

        # This file is autogenerated by skit
        # DO NOT EDIT MANUALLY

        require "sorbet-runtime"

        class Simple < T::Struct
          prop :name, String
        end
      RUBY

      expect(code).to eq(expected)
    end
  end
end
# rubocop:enable RSpec/DescribeClass
