# typed: strict
# frozen_string_literal: true

module Skit
  module JsonSchema
    class CodeGenerator
      extend T::Sig

      sig { params(module_definition: Definitions::Module, config: Config).void }
      def initialize(module_definition, config)
        @module_definition = module_definition
        @config = config
      end

      sig { returns(String) }
      def generate
        parts = []

        # Header
        parts << "# typed: #{@config.typed_strictness}"
        parts << "# frozen_string_literal: true"
        parts << ""
        parts << "# This file is autogenerated by skit"
        parts << "# DO NOT EDIT MANUALLY"
        parts << ""
        parts << 'require "sorbet-runtime"'
        parts << 'require "skit"' if const_types?

        if @config.module_name
          parts << ""
          # Start module
          module_parts = T.must(@config.module_name).split("::")
          module_parts.each_with_index do |module_part, index|
            parts << "#{"  " * index}module #{module_part}"
          end

          # Enum types first (within module)
          @module_definition.enum_types.each do |enum_type|
            parts << ""
            parts << generate_enum_class(enum_type, module_parts.length)
          end

          # Const types (within module)
          @module_definition.const_types.each do |const_type|
            parts << ""
            parts << generate_const_class(const_type, module_parts.length)
          end

          # Nested structs (within module)
          @module_definition.nested_structs.each do |nested_struct|
            parts << ""
            parts << generate_single_struct(nested_struct, module_parts.length)
          end

          # Main struct (within module)
          parts << ""
          parts << generate_single_struct(@module_definition.root_struct, module_parts.length)

          # End module
          module_parts.reverse.each_with_index do |_, index|
            parts << "#{"  " * (module_parts.length - index - 1)}end"
          end
        else
          # Enum types first
          @module_definition.enum_types.each do |enum_type|
            parts << ""
            parts << generate_enum_class(enum_type)
          end

          # Const types
          @module_definition.const_types.each do |const_type|
            parts << ""
            parts << generate_const_class(const_type)
          end

          # Nested structs
          @module_definition.nested_structs.each do |nested_struct|
            parts << ""
            parts << generate_single_struct(nested_struct)
          end

          # Main struct
          parts << ""
          parts << generate_single_struct(@module_definition.root_struct)
        end

        parts.join("\n")
      end

      private

      sig { returns(T::Boolean) }
      def const_types?
        !@module_definition.const_types.empty?
      end

      sig { params(enum_type: Definitions::EnumType, indent_level: Integer).returns(String) }
      def generate_enum_class(enum_type, indent_level = 0)
        lines = []
        base_indent = "  " * indent_level

        lines << "#{base_indent}class #{enum_type.class_name} < T::Enum"
        lines << "#{base_indent}  enums do"

        enum_type.values.each do |value| # rubocop:disable Style/HashEachMethods
          member_name = Definitions::EnumType.value_to_member_name(value)
          value_literal = Definitions::EnumType.value_literal(value)
          lines << "#{base_indent}    #{member_name} = new(#{value_literal})"
        end

        lines << "#{base_indent}  end"
        lines << "#{base_indent}end"

        lines.join("\n")
      end

      sig { params(const_type: Definitions::ConstType, indent_level: Integer).returns(String) }
      def generate_const_class(const_type, indent_level = 0)
        lines = []
        base_indent = "  " * indent_level

        lines << "#{base_indent}class #{const_type.class_name} < Skit::JsonSchema::Types::Const"
        lines << "#{base_indent}  VALUE = #{const_type.value_literal}"
        lines << "#{base_indent}end"

        lines.join("\n")
      end

      sig { params(struct_def: Definitions::Struct, indent_level: Integer).returns(String) }
      def generate_single_struct(struct_def, indent_level = 0)
        lines = []
        base_indent = "  " * indent_level

        # Description comment
        lines << "#{base_indent}# #{struct_def.description}" if struct_def.description

        # Class definition
        lines << "#{base_indent}class #{struct_def.class_name} < T::Struct"

        # Properties
        struct_def.properties.each do |property|
          property.comment&.split("\n")&.each do |comment_line|
            lines << "#{base_indent}  # #{comment_line}"
          end
          lines << "#{base_indent}  #{property.mutability} :#{property.name}, #{property.type.to_sorbet_type}"
        end

        lines << "#{base_indent}end"

        lines.join("\n")
      end
    end
  end
end
