# typed: strict
# frozen_string_literal: true

module Skit
  module JsonSchema
    class StructCodeGenerator
      extend T::Sig

      sig { params(struct_definition: Definitions::Struct, config: Config).void }
      def initialize(struct_definition, config)
        @struct_definition = struct_definition
        @config = config
      end

      sig { returns(String) }
      def generate
        parts = []

        # Header
        parts << "# typed: #{@config.typed_strictness}"
        parts << "# frozen_string_literal: true"
        parts << ""
        parts << "# This file is autogenerated by skit"
        parts << "# DO NOT EDIT MANUALLY"
        parts << ""
        parts << 'require "sorbet-runtime"'

        if @config.module_name
          parts << ""
          # Start module
          module_parts = T.must(@config.module_name).split("::")
          module_parts.each_with_index do |module_part, index|
            parts << "#{"  " * index}module #{module_part}"
          end

          # Nested structs first (within module)
          @struct_definition.nested_structs.each do |nested_struct|
            parts << ""
            parts << generate_single_struct(nested_struct, module_parts.length)
          end

          # Main struct (within module)
          parts << ""
          parts << generate_single_struct(@struct_definition, module_parts.length)

          # End module
          module_parts.reverse.each_with_index do |_, index|
            parts << "#{"  " * (module_parts.length - index - 1)}end"
          end
        else
          # Nested structs first
          @struct_definition.nested_structs.each do |nested_struct|
            parts << ""
            parts << generate_single_struct(nested_struct)
          end

          # Main struct
          parts << ""
          parts << generate_single_struct(@struct_definition)
        end

        parts.join("\n")
      end

      private

      sig { params(struct_def: Definitions::Struct, indent_level: Integer).returns(String) }
      def generate_single_struct(struct_def, indent_level = 0)
        lines = []
        base_indent = "  " * indent_level

        # Description comment
        lines << "#{base_indent}# #{struct_def.description}" if struct_def.description

        # Class definition
        lines << "#{base_indent}class #{struct_def.class_name} < T::Struct"

        # Properties
        struct_def.properties.each do |property|
          property.comment&.split("\n")&.each do |comment_line|
            lines << "#{base_indent}  # #{comment_line}"
          end
          lines << "#{base_indent}  #{property.mutability} :#{property.name}, #{property.type.to_sorbet_type}"
        end

        lines << "#{base_indent}end"

        lines.join("\n")
      end
    end
  end
end
