# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::Concurrent::Map; end
module ::Tapioca::SourceURI; end
module ActiveRecord::ConnectionAdapters::DatabaseStatements; end
module ActiveRecord::ConnectionAdapters::SchemaStatements; end
class Minitest::Assertion < StandardError; end
class Minitest::Test; end
